name: CD

on:
  push:
    branches:
      - develop

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build . -f Dockerfile -t molotovhammr/kozidataservice:latest

    - name: Log into registry
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to repository
      run: docker push molotovhammr/kozidataservice:latest
